// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetVpnBootstrap():Promise<main.VpnBootstrapData>;

export function Greet(arg1:string):Promise<string>;

export function ImportConfig(arg1:string):Promise<main.VpnBootstrapData>;

export function MeasureAllServerLatencies():Promise<main.VpnBootstrapData>;

export function MeasureSelectedServerLatency(arg1:string):Promise<main.VpnBootstrapData>;

export function SaveSelectedServer(arg1:string):Promise<void>;
