// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVpnBootstrap() {
  return window['go']['main']['App']['GetVpnBootstrap']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportConfig(arg1) {
  return window['go']['main']['App']['ImportConfig'](arg1);
}

export function MeasureAllServerLatencies() {
  return window['go']['main']['App']['MeasureAllServerLatencies']();
}

export function MeasureSelectedServerLatency(arg1) {
  return window['go']['main']['App']['MeasureSelectedServerLatency'](arg1);
}

export function SaveSelectedServer(arg1) {
  return window['go']['main']['App']['SaveSelectedServer'](arg1);
}
