// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetConnectionStatus():Promise<main.RuntimeStatus>;

export function GetDependencyStatus():Promise<main.DependencyStatus>;

export function GetVpnBootstrap():Promise<main.VpnBootstrapData>;

export function ImportConfig(arg1:string):Promise<main.VpnBootstrapData>;

export function InstallDependencies():Promise<string>;

export function MeasureAllServerLatencies():Promise<main.VpnBootstrapData>;

export function MeasureSelectedServerLatency(arg1:string):Promise<main.VpnBootstrapData>;

export function SaveSelectedServer(arg1:string):Promise<void>;
